name: nnti
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - matplotlib
  - pandas
  - numpy
  - notebook
  - protobuf
  - datasets
  - transformers
  - sentencepiece
  - peft
  - pyarrow
  - accelerate
  - scikit-learn
  - tensorboard
  - altair<5
  - h5py
  - wandb